baseurl = "http://localhost:1313/latest"
languageCode = "en-us"
theme = "hugo-docs"

# set by build script: title, baseurl
title = "Dgraph Documentation"

[params]
  # Place the latest version at the beginning so that version selector can
  # append '(latest)' to the version string
  versions = [
    "v0.7.5",
    "v0.7.4",
    "master"
  ]

[[menu.main]]
  name = "Users"
  url = "/users/"
  identifier = "users"
  weight = 1
